package com.example.assettracking.model;

import java.time.Instant;
import java.time.format.DateTimeFormatter;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@DynamoDBTable(tableName = "AssetEvents") // This must be the same as in DynamoDB
@Data
public class AssetEvent {
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBHashKey(attributeName = "asset")
	private long asset;

	@DynamoDBHashKey(attributeName = "createdAt")
	private long createdAt;

	@DynamoDBHashKey(attributeName = "trip")
	private long trip;

	@DynamoDBHashKey(attributeName = "x")
	private Double x;

	@DynamoDBHashKey(attributeName = "y")
	private Double y;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public long getAsset() {
		return asset;
	}

	public void setAsset(long asset) {
		this.asset = asset;
	}

	public long getCreatedAt() {
		return createdAt;
	}

	public String getCreatedAtISOStr() {
		Instant instant = Instant.ofEpochMilli(this.createdAt);

		// Format the Instant as an ISO 8601 string
		String isoDate = DateTimeFormatter.ISO_INSTANT.format(instant);
		return isoDate;

	}

	public void setCreatedAt(long createdAt) {
		this.createdAt = createdAt;
	}

	public long getTrip() {
		return trip;
	}

	public void setTrip(long trip) {
		this.trip = trip;
	}

	public Double getX() {
		return x;
	}

	public void setX(Double x) {
		this.x = x;
	}

	public Double getY() {
		return y;
	}

	public void setY(Double y) {
		this.y = y;
	}
	
	public AssetEventDTO toAssetEventDTO() {
		return new AssetEventDTO(this);
	}

}
